name: Build and Push devcontainer Images

on: 
  workflow_dispatch:
  schedule:
    - cron: '10 */6 * * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set date_tag
      id: var_date
      run: echo "date_tag=$(TZ="Asia/Taipei" date +"%Y%m%d%H%M%S")" >> $GITHUB_OUTPUT

    - name: Login to github container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image with devcontainer.json
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/angtsusiong/machi-koro-cpp-devcontainer
        cacheFrom: ghcr.io/angtsusiong/machi-koro-cpp-devcontainer
        imageTag: ${{ steps.var_date.outputs.date_tag }},latest
        push: always
